version: "3"
services:
  patisserie-database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: patisserie
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
